name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build docker image
      run: docker-compose build
    - name: Run app
      run: docker-compose up -d
    - name: Run tests
      run: docker-compose exec -T web python test.py
    